name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        env:
          DEFI_SDK_API_URL: wss://api-v4.zerion.io/
          DEFI_SDK_TESTNET_API_URL: wss://api-testnet.zerion.io/
          ZERION_API_URL: https://zpi.zerion.io/
          ZERION_TESTNET_API_URL: https://zpi-testnet.zerion.io/
          PROXY_URL: https://proxy.zerion.io/
          DEFI_SDK_TRANSACTIONS_API_URL: https://transactions.zerion.io
          DEFI_SDK_API_TOKEN: Zerion.0JOY6zZTTw6yl5Cvz9sdmXc7d5AhzVMG
          SOCIAL_API_URL: https://social.zerion.io/
          TEST_WALLET_ADDRESS: ${{ secrets.TEST_WALLET_ADDRESS }}
          FEATURE_SEND_FORM: on
          FEATURE_FOOTER_BUG_BUTTON: off
          FEATURE_PAYMASTER: on
          MIXPANEL_TOKEN_PUBLIC: ${{ secrets.MIXPANEL_TOKEN_PUBLIC_PROD }}
        run: |
          npm install
          npm run build:production

      - name: Compress build artifacts
        shell: bash
        run: |
          mv dist zerion-wallet-extension-${{github.ref_name}}
          zip -r zerion-wallet-extension-${{github.ref_name}}.zip zerion-wallet-extension-${{github.ref_name}}
          tar czf zerion-wallet-extension-${{github.ref_name}}.tar.gz --directory=zerion-wallet-extension-${{github.ref_name}} .

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: 'zerion-wallet-extension-${{github.ref_name}}.zip,zerion-wallet-extension-${{github.ref_name}}.tar.gz'

      - name: Notify release
        id: notify-release
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04JLLQRB43'
          payload: |
            {
              "text": "New release",
              "icon_emoji": ":gift:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ format('{0}/{1}/releases/tag/{2}', github.server_url, github.repository, github.ref_name)}}|${{ github.ref_name }}>"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*Created by:* ${{ github.triggering_actor }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_AUTH_TOKEN }}
